### ISSUE TITLE
error installing models: Directory not empty:

### ISSUE THREAD

**Issue by ShailNair** [mdmparis/defense-finder#15]
Hi, 

I have a server connection problem while installing anything from GitHub. So, I downloaded the defensefinder models.tar.gz file
When I run  
`macsydata install /home/defense-finder-models-1.1.0.tar.gz `

I get the following error 
`Extracting defense-finder-models (1.1.0).
Removing old models /tmp/tmp-macsy-cache/local/defense-finder-models/1.1.0/defense-finder-models
Traceback (most recent call last):
  File "/home/miniconda3/envs/defensefinder/bin/macsydata", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/defensefinder/lib/python3.7/site-packages/macsypy/scripts/macsydata.py", line 938, in main
    parsed_args.func(parsed_args)
  File "/home/miniconda3/envs/defensefinder/lib/python3.7/site-packages/macsypy/scripts/macsydata.py", line 335, in do_install
    cached_pack = model_index.unarchive_package(arch_path)
  File "/home/miniconda3/envs/defensefinder/lib/python3.7/site-packages/macsypy/package.py", line 95, in unarchive_package
    os.rename(unarchive_pack, dest_unarchive_path)
OSError: [Errno 39] Directory not empty: '/tmp/tmp-macsy-cache/local/defense-finder-models/1.1.0/defense-finder-models/LICENSE' -> '/tmp/tmp-macsy-cache/local/defense-finder-models/1.1.0/defense-finder-models'`

Things I tried:
1) `Clearing /tmp/tmp-macsy-cache/local/defense-finder-models/1.1.0/defense-finder-models/`
2) deleting `/tmp/tmp-macsy-cache/`
3) use `macsydata install` with --force/--user parameter

In all cases, the macsydata.py script decompresses the content of the tar file into the temp directory and then throws the same error.

**Comment by ShailNair** [comment]
[Fixed](https://github.com/gem-pasteur/macsyfinder/issues/50#issuecomment-1183786551)
