### ISSUE TITLE
Install fails on the update step

### ISSUE THREAD

**Issue by angusangermeyer** [mdmparis/defense-finder#2]
I had the the TLS issue for pip, but the stackoverflow link in the readme seemed to work. However, when  I then run `defense-finder update` I'm getting an error with colorlog:
```
Traceback (most recent call last):
  File "/Users/angusangermeyer/opt/miniconda3/bin/macsydata", line 8, in <module>
    sys.exit(main())
  File "/Users/angusangermeyer/opt/miniconda3/lib/python3.7/site-packages/macsypy/scripts/macsydata.py", line 824, in main
    macsypy.init_logger()
  File "/Users/angusangermeyer/opt/miniconda3/lib/python3.7/site-packages/macsypy/__init__.py", line 48, in init_logger
    logging = colorlog.logging.logging
AttributeError: module 'colorlog' has no attribute 'logging'
```

**Comment by pentamorfico** [comment]
The same thing happened to me! I just ran `pip3 install "colorlog==4.1.0"` within the defensefinder environment and it worked!

**Comment by Alexandre-Herve** [comment]
Hey there, coming late to the party: the issue comes from MacsyFinder which did not specify a colorlog version, and colorlog which recently sent a breaking change with a minor increment. I'll see if I can do something, in the meantime @pentamorfico's fix works, thanks :ok_hand:
