### ISSUE TITLE
Macsyfinder best_solution.tsv parsing error and suggested solution

### ISSUE THREAD

**Issue by hsbi** [mdmparis/defense-finder#20]
Hi, thanks for creating an interesting tool!

I encountered the following error while running defense-finder thus: `defense-finder run <MY_GENOME>.faa --models-dir <PATH_TO_MY_MACSYFINDER_MODELS>`

`###################### Computing best solutions ######################
Computing best solutions for UserReplicon (nb of candidate systems 3)
It took 0.00sec to find best solution (8.00) for replicon UserReplicon

################### Writing down results in 'Cas' ####################
END

Traceback (most recent call last):
  File "<PATH_TO_DEFENSEFINDER>/bin/defense-finder", line 8, in <module>
    sys.exit(cli())
  File <PATH_TO_DEFENSEFINDER>/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/<PATH_TO_DEFENSEFINDER>/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "<PATH_TO_DEFENSEFINDER>/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "<PATH_TO_DEFENSEFINDER>/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "<PATH_TO_DEFENSEFINDER>/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "<PATH_TO_DEFENSEFINDER>/lib/python3.8/site-packages/defense_finder_cli/main.py", line 76, in run
    defense_finder_posttreat.run(tmp_dir, outdir)
  File "<PATH_TO_DEFENSEFINDER>/lib/python3.8/site-packages/defense_finder_posttreat/__init__.py", line 9, in run
    bs = best_solution.get(tmp_dir)
  File "<PATH_TO_DEFENSEFINDER>/lib/python3.8/site-packages/defense_finder_posttreat/best_solution.py", line 12, in get
    return format_best_solution(acc)
  File "<PATH_TO_DEFENSEFINDER>/lib/python3.8/site-packages/defense_finder_posttreat/best_solution.py", line 55, in format_best_solution
    gene_ref = l['model_fqn']
KeyError: 'model_fqn'`

After doing some digging, it seems like the issue was that the Macsyfinder output file best_solution.tsv wasn't being parsed correctly by defense-finder. I was able to resolve the issue and get (what seems like) the correct defense-finder outputs by replacing  line 26 `if "No Systems found" in ' '.join(data[2]):` with `if "No Systems found" in ' '.join(data[3]):` and line 29 `data = data[3:]` with `data = data[4:]`, both in best_solution.py

Just putting this here in case anyone else has this same issue. Sorry if my formatting is garbage.

**Comment by hsbi** [comment]
Update: I reinstalled defense-finder after experiencing some unrelated issues while running and it seems now the parsing error doesn't happen. No idea why Macsyfinder outputted files with extra header lines when I ran it earlier :/
