### ISSUE TITLE
IndexError: list index out of range when running 'defense-finder update'

### ISSUE THREAD

**Issue by ZongzhiWu** [mdmparis/defense-finder#21]
**When I ran the command 'defense-finder update' on HPC, I came across the following issue:**
Downloading defense-finder-models (1.2.2).
Extracting defense-finder-models (1.2.2).
Removing old models /tmp/tmp-macsy-cache/mdmparis/defense-finder-models/1.2.2/defense-finder-models
Traceback (most recent call last):
  File "/gpfs/share/home/2201112334/miniconda3/bin/macsydata", line 8, in <module>
    sys.exit(main())
  File "/gpfs/share/home/2201112334/miniconda3/lib/python3.9/site-packages/macsypy/scripts/macsydata.py", line 938, in main
    parsed_args.func(parsed_args)
  File "/gpfs/share/home/2201112334/miniconda3/lib/python3.9/site-packages/macsypy/scripts/macsydata.py", line 348, in do_install
    dest = config.models_dir()[0]
IndexError: list index out of range

**Comment by ZongzhiWu** [comment]
It has been solved after running this command 'macsydata install -U -u --org mdmparis defense-finder-models'.

**Comment by ZongzhiWu** [comment]
closed
