### ISSUE TITLE
Failed to run via singularity

### ISSUE THREAD

**Issue by YuyaKiguchi** [mdmparis/defense-finder#3]
Hi,

Thanks for great tool for analyzing the phage defense system.
I made the image of singularity, and run the defense-finder.
Unfortunately, I got the error below. Could you solve this problem?

> Traceback (most recent call last):
  File "/usr/local/bin/macsyfinder", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/macsypy/scripts/macsyfinder.py", line 837, in main
    macsypy.init_logger(log_file=os.path.join(config.working_dir(), config.log_file()),
  File "/usr/local/lib/python3.8/dist-packages/macsypy/__init__.py", line 48, in init_logger
    logging = colorlog.logging.logging
AttributeError: module 'colorlog' has no attribute 'logging'
Traceback (most recent call last):
  File "/usr/local/bin/defense-finder", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/defense_finder_cli/main.py", line 46, in run
    defense_finder_posttreat.run(outdir)
  File "/usr/local/lib/python3.8/dist-packages/defense_finder_posttreat/__init__.py", line 7, in run
    bs = best_solutions.get()
  File "/usr/local/lib/python3.8/dist-packages/defense_finder_posttreat/best_solutions.py", line 4, in get
    parsed = parse_all()
  File "/usr/local/lib/python3.8/dist-packages/defense_finder_posttreat/best_solutions.py", line 8, in parse_all
    tsv_file = open('/tmp/defense-finder/all_best_solutions.tsv')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/defense-finder/all_best_solutions.tsv'

**Comment by charlottecc** [comment]
Hi, 
I'm having this same issue, has any one figured out how to fix it? 
Thanks!
