### ISSUE TITLE
macsyfinder: "No such model definition: 'CasFinder'"

### ISSUE THREAD

**Issue by liaohu1231** [mdmparis/defense-finder#36]
2023-11-02 14:09:40 | INFO     | Received file bins/1-1_bin.1/1-1_bin.1.faa
 2023-11-02 14:09:40 | WARNING  | Out directory /home/liaohu01/thawed_soil_metagenome already exists. Existing DefenseFinder output will be overwritten
 2023-11-02 14:09:40 | WARNING  | Temporary directory /home/liaohu01/thawed_soil_metagenome/defense-finder-tmp already exists. Overwriting it.
 2023-11-02 14:09:49 | INFO     | Running DefenseFinder
macsyfinder: "No such model definition: 'CasFinder'"

**Comment by liliancaesarbio** [comment]
I am having the same issue:

"macsyfinder: "No such model definition: 'CasFinder'""

**Comment by eranbosis** [comment]
Hi everyone,
I am having the same issue:
macsyfinder: "No such model definition: 'CasFinder'"
The previous version of defense-finder worked properly.
Any ideas how to resolve it?
Thanks,
Eran

**Comment by gjzheng** [comment]
I am having the same issue too
macsyfinder: "No such model definition: 'CasFinder'"

**Comment by gjzheng** [comment]
finally I solve my problem by download the CasFinder file on https://github.com/macsy-models/CasFinder or you can Use command like : macsydata install CasFinder . Then move the ‘’CasFinder‘’  to a folder which must contain the original defense-finder-models . then use --models-dir to specific your models place. and you can finally run defense-finder

**Comment by eranbosis** [comment]
Thanks for the info. In my case, there was a problem with the defense-finder models. So, I deleted the /data directory where the models are stored and re-installed them using **defense-finder update** and the name of the directory where I store the models.

**Comment by balamalaha** [comment]
I countered the error "KeyError: "No such model definition: 'RloC'"". How can I solve it?

**Comment by balamalaha** [comment]
Hi this is the error I got. I installed the latest version of the program and database. I have checked that RolC is in the database files.

Traceback (most recent call last):
  File "/home/ana/.conda/envs/main/bin/defense-finder", line 8, in <module>
    sys.exit(cli())
  File "/home/ana/.local/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ana/.local/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ana/.local/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ana/.local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ana/.local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ana/.conda/envs/main/lib/python3.7/site-packages/defense_finder_cli/main.py", line 143, in run
    defense_finder.run(protein_file_name, dbtype, workers, coverage, tmp_dir, models_dir, no_cut_ga, loglevel)
  File "/home/ana/.conda/envs/main/lib/python3.7/site-packages/defense_finder/__init__.py", line 29, in run
    macsyfinder.main(args=msf_cmd)
  File "/home/ana/.local/lib/python3.7/site-packages/macsypy/scripts/macsyfinder.py", line 903, in main
    all_systems, rejected_clusters = search_systems(config, model_registry, models_def_to_detect, logger)
  File "/home/ana/.local/lib/python3.7/site-packages/macsypy/scripts/macsyfinder.py", line 483, in search_systems
    parser.parse(models_def_to_detect)
  File "/home/ana/.local/lib/python3.7/site-packages/macsypy/definition_parser.py", line 80, in parse
    model_location = self.model_registry[def_loc.family_name]
  File "/home/ana/.local/lib/python3.7/site-packages/macsypy/registries.py", line 119, in __getitem__
    raise KeyError(f"No such model definition: '{name}'")
KeyError: "No such model definition: 'RloC'"
