### ISSUE TITLE
Issue with defense_finder_posttreat for "aa" protein files

### ISSUE THREAD

**Issue by rsheppar** [mdmparis/defense-finder#37]
Hello,  I installed Defense-Finder for a user.    I have no trouble with .nt files (below).  However, when given .aa files, the package seems to run, but does not properly collect the various temporary files into the file set the user expects.  I have used a number of different python versions with the exact same behavior.  Any insight would be appreciated.  
                          Ray
Works:
@h1 defense_finder]$ srun -p general -A staff --nodes=1 --mem=200G --cpus-per-task=48 --time=04:00:00 --pty bash
[rsheppar@c78 defense_finder]$  defense-finder run 7.nt  -o test.out
 2023-11-02 11:46:13 | INFO     | Received file 7.nt
 2023-11-02 11:46:13 | WARNING  | Out directory /geode2/home/u070/rsheppar/Quartz/defense_finder/test.out already exists. Existing DefenseFinder output will be overwritten
 2023-11-02 11:46:13 | WARNING  | Temporary directory /geode2/home/u070/rsheppar/Quartz/defense_finder/test.out/defense-finder-tmp already exists. Overwriting it.
 2023-11-02 11:46:13 | INFO     | 7.nt is a nucleotide fasta file. Prodigal will annotate the CDS
 2023-11-02 12:05:07 | INFO     | Prodigal annotated 1700 replicons
 2023-11-02 12:06:36 | INFO     | Protein files written in /geode2/home/u070/rsheppar/Quartz/defense_finder/test.out/7.prt
 2023-11-02 12:06:36 | INFO     | 1435169 CDS were annotated
 2023-11-02 12:06:36 | INFO     | Running DefenseFinder
 2023-11-02 12:38:08 | INFO     | Post-treatment of the data
 2023-11-02 12:38:16 | INFO     | Analysis results were written to /geode2/home/u070/rsheppar/Quartz/defense_finder/test.out
 2023-11-02 12:38:17 | INFO     | Analysis done. Please cite :

Tesson F., Hervé A. , Mordret E., Touchon M., d’Humières C., Cury J., Bernheim A., 2022, Nature Communication
Systematic and quantitative view of the antiviral arsenal of prokaryotes

DefenseFinder relies on MacSyFinder :

Macsydata 2.1.2
Python 3.10.5 (main, Jul 28 2022, 13:35:27) [GCC 9.3.0]

MacsyFinder is distributed under the terms of the GNU General Public License (GPLv3).
See the COPYING file for details.

If you use this software please cite:
Néron, Bertrand; Denise, Rémi; Coluzzi, Charles; Touchon, Marie; Rocha, Eduardo P.C.; Abby, Sophie S.
MacSyFinder v2: Improved modelling and search engine to identify molecular systems in genomes.
Peer Community Journal, Volume 3 (2023), article no. e28. doi : 10.24072/pcjournal.250.
https://peercommunityjournal.org/articles/10.24072/pcjournal.250/

Does not work:

[rsheppar@c78 defense_finder]$  defense-finder run 7.aa  -o test_aa.out
 2023-11-02 14:48:35 | INFO     | Received file 7.aa
 2023-11-02 14:48:35 | WARNING  | Out directory /geode2/home/u070/rsheppar/Quartz/defense_finder/test_aa.out already exists. Existing DefenseFinder output will be overwritten
 2023-11-02 14:48:35 | WARNING  | Temporary directory /geode2/home/u070/rsheppar/Quartz/defense_finder/test_aa.out/defense-finder-tmp already exists. Overwriting it.
 2023-11-02 14:48:37 | INFO     | Running DefenseFinder
 2023-11-02 14:49:03 | INFO     | Post-treatment of the data
Traceback (most recent call last):
  File "/N/u/rsheppar/Quartz/.local/bin/defense-finder", line 8, in <module>
    sys.exit(cli())
  File "/N/u/rsheppar/Quartz/.local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/N/u/rsheppar/Quartz/.local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/N/u/rsheppar/Quartz/.local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/N/u/rsheppar/Quartz/.local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/N/u/rsheppar/Quartz/.local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/N/u/rsheppar/Quartz/.local/lib/python3.10/site-packages/defense_finder_cli/main.py", line 145, in run
    defense_finder_posttreat.run(tmp_dir, outdir, os.path.splitext(os.path.basename(filename))[0])
  File "/N/u/rsheppar/Quartz/.local/lib/python3.10/site-packages/defense_finder_posttreat/__init__.py", line 11, in run
    bs = best_solution.get(tmp_dir)
  File "/N/u/rsheppar/Quartz/.local/lib/python3.10/site-packages/defense_finder_posttreat/best_solution.py", line 15, in get
    return format_best_solution(acc)
  File "/N/u/rsheppar/Quartz/.local/lib/python3.10/site-packages/defense_finder_posttreat/best_solution.py", line 56, in format_best_solution
    gene_ref_elements = split_def_name(gene_ref)
  File "/N/u/rsheppar/Quartz/.local/lib/python3.10/site-packages/macsypy/registries.py", line 49, in split_def_name
    split = fqn.split(_SEPARATOR)
AttributeError: 'NoneType' object has no attribute 'split'

FYI, I had to append "txt" to the file name to upload here.  It was run as 7.aa.
    Ray again

[7.aa.txt](https://github.com/mdmparis/defense-finder/files/13273389/7.aa.txt)

**Comment by jeanrjc** [comment]
Hello

It's because the protein names are not ordered, they should be in the format `xxxx_001` so defensefinder knows that protein xxxx_001 is next to protein xxxx_002 (the number of 0 does not matter). When using prodigal, it correctly gives the correct names. 
So here, since you're dataset is not ordered, you would need to use the option `--db-type unordered`, but I just notice that there is a bug with this option. I opened another issue (#40) to track this bug. 

So meanwhile, if you have the nucleotide sequence, use it to reannotate your CDS with the protein ordered and you'll be fine.

**Comment by rsheppar** [comment]
Thank you Jeanrjc.  I will pass along the solution and follow #40.  Happy holidays.
  Ray again
