### ISSUE TITLE
Defense finder failed to run

### ISSUE THREAD

**Issue by sujeetpowar** [mdmparis/defense-finder#39]
Hi,
I am getting this error when I try to run defense finder on gembase format(protein).

Traceback (most recent call last):
  File "/home/sujeet/miniconda3/envs/defensefinder/bin/defense-finder", line 10, in <module>
    sys.exit(cli())
  File "/home/sujeet/miniconda3/envs/defensefinder/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/sujeet/miniconda3/envs/defensefinder/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/sujeet/miniconda3/envs/defensefinder/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sujeet/miniconda3/envs/defensefinder/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sujeet/miniconda3/envs/defensefinder/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/sujeet/miniconda3/envs/defensefinder/lib/python3.10/site-packages/defense_finder_cli/main.py", line 143, in run
    defense_finder.run(protein_file_name, dbtype, workers, coverage, tmp_dir, models_dir, no_cut_ga, loglevel)
  File "/home/sujeet/miniconda3/envs/defensefinder/lib/python3.10/site-packages/defense_finder/__init__.py", line 29, in run
    macsyfinder.main(args=msf_cmd)
  File "/home/sujeet/miniconda3/envs/defensefinder/lib/python3.10/site-packages/macsypy/scripts/macsyfinder.py", line 1193, in main
    all_systems, rejected_candidates = search_systems(config, model_registry, models_def_to_detect, logger)
  File "/home/sujeet/miniconda3/envs/defensefinder/lib/python3.10/site-packages/macsypy/scripts/macsyfinder.py", line 577, in search_systems
    systems, rejected_candidates = _search_in_ordered_replicon(hits_by_replicon, models_to_detect,
  File "/home/sujeet/miniconda3/envs/defensefinder/lib/python3.10/site-packages/macsypy/scripts/macsyfinder.py", line 606, in _search_in_ordered_replicon
    rep_info = rep_db[rep_name]
  File "/home/sujeet/miniconda3/envs/defensefinder/lib/python3.10/site-packages/macsypy/database.py", line 437, in __getitem__
    return self._DB[replicon_name]
KeyError: 'HEPY.1223.00003.0001i'

Could you please let me know how to fix this error?

**Comment by jeanrjc** [comment]
Hello, thanks for the report.

I'm closing this issue in favor of the one you posted on macsyfinder : https://github.com/gem-pasteur/macsyfinder/issues/68
