### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by liucong2016** [mdmparis/defense-finder#44]
i met a question. can you give me some advice?

(vs2) defense-finder run --db-type gembase bacteria_cluster-23.10.4-protein.fa --models-dir /home/liu-c/.macsyfinder/models -w 60

2024-01-06 17:09:56 | INFO     | Received file bacteria_cluster-23.10.4-protein.fa
 2024-01-06 17:09:56 | WARNING  | Out directory /home/liu-c/virus-data/tuanjuti-virome/defense_finder_output-24.1.5 already exists. Existing DefenseFinder output will be overwritten
 2024-01-06 17:09:56 | WARNING  | Temporary directory /home/liu-c/virus-data/tuanjuti-virome/defense_finder_output-24.1.5/defense-finder-tmp already exists. Overwriting it.
 2024-01-06 17:09:56 | INFO     | Running DefenseFinder
 2024-01-06 21:03:05 | INFO     | Post-treatment of the data
Traceback (most recent call last):
  File "/software1/envs/vs2/bin/defense-finder", line 8, in <module>
    sys.exit(cli())
  File "/software1/envs/vs2/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/software1/envs/vs2/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/software1/envs/vs2/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/software1/envs/vs2/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/software1/envs/vs2/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/software1/envs/vs2/lib/python3.10/site-packages/defense_finder_cli/main.py", line 145, in run
    defense_finder_posttreat.run(tmp_dir, outdir, os.path.splitext(os.path.basename(filename))[0])
  File "/software1/envs/vs2/lib/python3.10/site-packages/defense_finder_posttreat/__init__.py", line 11, in run
    bs = best_solution.get(tmp_dir)
  File "/software1/envs/vs2/lib/python3.10/site-packages/defense_finder_posttreat/best_solution.py", line 15, in get
    return format_best_solution(acc)
  File "/software1/envs/vs2/lib/python3.10/site-packages/defense_finder_posttreat/best_solution.py", line 56, in format_best_solution
    gene_ref_elements = split_def_name(gene_ref)
  File "/software1/envs/vs2/lib/python3.10/site-packages/macsypy/registries.py", line 49, in split_def_name
    split = fqn.split(_SEPARATOR)
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by jeanrjc** [comment]
your protein file is probably not gembase
