### ISSUE TITLE
Error upon models update

### ISSUE THREAD

**Issue by oliveira-lab** [mdmparis/defense-finder#8]
Hi there, 

I am trying to update the defense finder models but I consistently stumble upon an index error.
Can you please help?
Thanks!
Pedro

$ defense-finder update
Downloading defense-finder-models (1.0.0).
Extracting defense-finder-models (1.0.0).
Removing old models /var/folders/d1/7b_cc8350fv16cmp7z6vy4rh0000gn/T/tmp-macsy-cache/mdmparis/defense-finder-models/1.0.0/defense-finder-models
Traceback (most recent call last):
  File "/Users/pedrooliveira/opt/miniconda3/bin/macsydata", line 8, in <module>
    sys.exit(main())
  File "/Users/pedrooliveira/opt/miniconda3/lib/python3.9/site-packages/macsypy/scripts/macsydata.py", line 938, in main
    parsed_args.func(parsed_args)
  File "/Users/pedrooliveira/opt/miniconda3/lib/python3.9/site-packages/macsypy/scripts/macsydata.py", line 348, in do_install
    dest = config.models_dir()[0]
IndexError: list index out of range

**Comment by gucedac** [comment]
Hi. I have the same problem.
Please someone can help us!
Thanks

**Comment by Alexandre-Herve** [comment]
Hi there, would you please try this command and tell me if it works and if you can use defense-finder properly after that:

```
macsydata install -U -u --org mdmparis defense-finder-models
```

This is the command that is internally run when calling `defense-finder update`, with an addition of the `-u` flag to specify a user directory install.

**Comment by Tsingsjeen** [comment]
> 

I think this commands work better!

**Comment by bellasmith121995** [comment]
I tried the aforementioned fixes and I keep getting the following errors: 

```
Downloading defense-finder-models (1.1.0).
Traceback (most recent call last):
  File "~/miniconda3/envs/defensefinder/bin/macsydata", line 8, in <module>
    sys.exit(main())
  File "~/miniconda3/envs/defensefinder/lib/python3.7/site-packages/macsypy/scripts/macsydata.py", line 938, in main
    parsed_args.func(parsed_args)
  File "~/miniconda3/envs/defensefinder/lib/python3.7/site-packages/macsypy/scripts/macsydata.py", line 329, in do_install
    arch_path = model_index.download(pack_name, str(target_vers))
  File "~/miniconda3/envs/defensefinder/lib/python3.7/site-packages/macsypy/package.py", line 253, in download
    os.makedirs(package_cache)
  File "~/miniconda3/envs/defensefinder/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/tmp/tmp-macsy-cache/mdmparis'
```
Any further suggestions?

**Comment by Alexandre-Herve** [comment]
@bellasmith121995 you seem to not have the permissions to write to your `/tmp` directory.
Can you try the same command with `sudo`?

**Comment by bellasmith121995** [comment]
I ended up finding a fix. Thanks!

**Comment by jeanrjc** [comment]
Hello,

Until now, even though you could install `defense-finder-models` in the repository of your choice with one of the above methods, `defense-finder` had no way to know where to look for it.
This is now fixed. You have the option `--models-dir` for the `update` and `run` command that tells `defense-finder` where to install/update and which models to use. You can update defense-finder by running in the environment where you installed it : `pip install -U mdmparis-defense-finder`

Best
